version: '2'
services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        command: mongod --smallfiles

    # scraper:
    #     build: ../gitpoint-api-trending-scraper
    #     container_name: gp-trending-scraper
    #     environment:
    #         LOGGER_NAME: GP-Trending-Scraper
    #         LOGGER_LEVEL: trace
    #         MONGODB_HOST: mongodb
    #         MONGODB_PORT: 27017
    #         MONGODB_DB: gitpoint
    #         CRON_PATTERN: '0 * * * * *'
    #     depends_on:
    #         - "mongodb"

    api:
        build: .
        container_name: gp-api
        environment:
            LOGGER_LEVEL: trace
            LOGGER_NAME: GP-API
            MONGODB_HOST: mongodb
            MONGODB_PORT: 27017
            MONGODB_DB: gitpoint
            HTTP_PORT: 9090
        depends_on:
            - "mongodb"
        ports:
            - 9090:9090
