version: '3'
services:
    nginx:
        build: ./nginx
        container_name: gp-api-nginx
        ports:
            - 8080:8080
        depends_on:
            - "api"
        links:
            - api

    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        command: mongod --smallfiles

    api:
        build: .
        container_name: gp-api
        environment:
            LOGGER_LEVEL: trace
            LOGGER_NAME: GP-API
            MONGODB_HOST: mongodb
            MONGODB_PORT: 27017
            MONGODB_DB: gitpoint
            HTTP_PORT: 9090
        depends_on:
            - "mongodb"
        ports:
            - 9090:9090
        volumes:
            - ./:/opt/app

    scraper:
        build: ../gitpoint-api-trending-scraper
        container_name: gp-trending-scraper
        environment:
            LOGGER_NAME: GP-Trending-Scraper
            LOGGER_LEVEL: trace
            MONGODB_HOST: mongodb
            MONGODB_PORT: 27017
            MONGODB_DB: gitpoint
            CRON_PATTERN: '0 * * * * *'
        depends_on:
            - "mongodb"
